#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/helpers/function

input(){
    while true
    do
        echo "Username does not contain special characters and must be 5 characters in length."
        read -r -p "Select the name of the connection you want to create (Instant, painless) [0 = Exit]: " remote_name
        echo
        if validate_user "${remote_name}" || [ "${remote_name}" == "0" ]; then
            break
        else
            printf "%s\n" "${RED}Connection name incorrectly. Please re-enter.${NC}"
        fi
    done
}

config_rclone(){
    rclone config create "${remote_name}" drive config_is_local false scope drive use_trash false
}

_run(){
    input

    if [ "${remote_name}" == "0" ]; then
        printf "%s\n" "${RED}Cancel action.${NC}"
    else
        config_rclone
    fi
}

remote_name=""

_run
menu_ggdrive