#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/helpers/function

confirm_destroy(){
    while true
    do
        read -r -p "You want to delete the backup ? (y/n) " promt_destroy
        echo
        if [[ "${promt_destroy}" =~ ^([yY])$ || "${promt_destroy}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
        fi
    done
}

select_backup(){
    echo "Select now you want to restore: "
    selects=$(rclone lsf "${remote}":"${IPADDRESS}")
    for entry in ${selects}; do
        select=${entry///}
        dates+=("${select}")
    done
    PS3="Enter your choice [0 = Exit]: "
    select date in "${dates[@]}"
    do
        date=${date}
        break
    done
}

choose_domain(){
    echo "Select the domain name you want to delete: "
    selects=$(rclone lsf "${remote}":"${IPADDRESS}"/"${date}")
    for entry in ${selects}; do
        select=${entry///}
        domains+=("${select}")
    done
    PS3="Enter your choice [0 = Exit]: "
    select domain in "${domains[@]}"
    do
        domain=${domain}
        break
    done
}

_run(){
    select_backup
    if [ -z "${date}" ]; then
        clear
        printf "%s\n" "${GREEN}You have Canceled backup deleted.${NC}"
    else
        choose_domain

        if [ -z "${domain}" ]; then
            clear
            printf "%s\n" "${GREEN}You have Canceled backup deleted.${NC}"
        else
            rclone delete "${remote}":/"${IPADDRESS}"/"${date}"/"${domain}" --rmdirs > /dev/null  2>&1
            rclone cleanup "${remote}":"${IPADDRESS}" > /dev/null  2>&1
            rm -rf /home/backup/"${date}"/"${domain}"
            clear
            printf "%s\n" "${GREEN}Delete backup success.${NC}"
        fi
    fi
}

if [ -f "/root/.config/rclone/rclone.conf" ]; then
    date=""
    remote=""
    domain=""
    promt_destroy="n"
    confirm_destroy
    if [[ "${promt_destroy}" =~ ^([yY])$ ]]; then
        if [[ $(ls -A "${USER_DIR}") ]]; then
            select_remote
            if [ -z "${remote}" ]; then
                clear
                printf "%s\n" "${GREEN}You have Canceled backup deleted.${NC}"
            else
                _run
            fi
        else
            printf "%s\n" "${RED}There are no domain names on VPS.${NC}"
        fi
    else
        clear
        printf "%s\n" "${GREEN}You have Canceled backup deleted.${NC}"
    fi
else
    printf "%s\n" "${RED}You have not connected with Google Drive yet.${NC}"
fi
menu_ggdrive