#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

confirm_destroy(){
    while true
    do
        read -r -p "You want to delete the backup ? (y/n) " promt_destroy
        echo
        if [[ "${promt_destroy}" =~ ^([yY])$ || "${promt_destroy}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
        fi
    done
}

_run(){
    promt_destroy=""
    remote=""
    confirm_destroy
    if [[ "${promt_destroy}" =~ ^([yY])$ ]]; then
        select_remote
        if [ -z "${remote}" ]; then
            clear
            printf "%s\n" "${RED}You have Canceled the operation.${NC}"
        else
            rclone config delete "${remote}"
            clear
            printf "%s\n" "${GREEN}Delete remote success.${NC}"
        fi
    fi
}

if [ -f "/root/.config/rclone/rclone.conf" ]; then
    _run
else
    clear
    printf "%s\n" "${RED}You have not configured a connection to Google Drive.${NC}"
fi
menu_ggdrive