#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

printf "%s===================%s\n" "${GREEN}" "${NC}"
printf "%sChange the Admin port%s\n" "${GREEN}" "${NC}"
printf "%s===================%s\n" "${GREEN}" "${NC}"

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    current_port=$(grep -w "admin_port" "${FILE_INFO}" | cut -f2 -d'=')
    csf_port=$(grep -w "csf_port" "${FILE_INFO}" | cut -f2 -d'=')
    ftp_port=$(grep -w "ftp_port" "${FILE_INFO}" | cut -f2 -d'=')
    ssh_port=$(grep -w "Port" /etc/ssh/sshd_config | cut -f2 -d" ")
}

input(){
    clear
    while true
    do
        read -r -p "Enter the port you want to use [0 = Exit]: " new_port
        if [[ ${new_port} =~ ^-?[0-9]+$ ]]; then
            break
        else
            printf "%s\n" "${RED}Port is incorrect format, please re-enter.${NC}"
        fi
    done
}

check_port(){
    if [ -z "${new_port}" ]; then
        ALERT=$(printf "%s\n" "${RED}You have not entered Port.${NC}")
    fi

    if [[ "${new_port}" == "${current_port}" ]]; then
        ALERT=$(printf "%s\n" "${RED}Port you enter the current Port Admin inclusions.${NC}")
    fi

    if [[ "${new_port}" == "${ssh_port}" || "${new_port}" == "${csf_port}" || "${new_port}" == "${ftp_port}" ]]; then
        ALERT=$(printf "%s\n" "${RED}The port you selected is already in use. Please select another port.${NC}")
    fi

    if [[ "${new_port}" == "22" || "${new_port}" == "11211" || "${new_port}" == "6379" ]]; then
        ALERT=$(printf "%s\n" "${RED}The port you selected is already in use. Please select another port.${NC}")
    fi

    if check_port_exists "${ftp_port}"; then
        ALERT=$(printf "%s\n" "${RED}Port is already in use. Please change the SSH port.${NC}")
    fi
}

_change_port(){
    echo "Register with SSH port ..."
   	echo ""
   	sleep 1
    sed -i "s/,${current_port}/,${new_port}/g" /etc/csf/csf.conf
    sed -i "s/${current_port}/${new_port}/g" /etc/nginx/web_apps.conf
    sed -i '/admin_port=/d' "${FILE_INFO}"
    echo "admin_port=${new_port}" >> "${FILE_INFO}"
    csf -x
    csf -e
    clear
    printf "%s\n" "${GREEN}Changed the Port Admin to ${new_port} success.${NC}"
}

_run(){
    set_var
    check_port
    if [ -z "${ALERT}" ]; then
        _change_port
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

new_port=""
ALERT=""
input
if [[ "${new_port}" == "0" ]]; then
    clear
    printf "%s\n" "${RED}You have chosen to cancel the Port changes.${NC}"
else
    _run
fi
menu_admin