#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=================================%s\n" "${GREEN}" "${NC}"
printf "%s  Check account information      %s\n  " "${GREEN}" "${NC}"
printf "%s=================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Admin Tool login information%s\n" "${GREEN}" "${NC}"
    printf "%s2. PhpMyAdmin credentials%s\n" "${GREEN}" "${NC}"
    printf "%s3. Test SSH Port%s\n" "${GREEN}" "${NC}"
    printf "%s4. Information by website%s\n" "${GREEN}" "${NC}"
    printf "%s ================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; c_tool ;;
        2) clear; pma_info ;;
        3) clear; ssh_info ;;
        4) clear; user_info ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done