#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s===========================%s\n" "${GREEN}" "${NC}"
printf "%s   Admin Tool Management   %s\n" "${GREEN}" "${NC}"
printf "%s===========================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Update phpMyAdmin%s\n" "${GREEN}" "${NC}"
    printf "%s2. Updating phpSysInfo%s\n" "${GREEN}" "${NC}"
    printf "%s3. Update Opcache Panel%s\n" "${GREEN}" "${NC}"
    printf "%s4. Update Memcached Admin%s\n" "${GREEN}" "${NC}"
    printf "%s5. Update Redis Admin%s\n" "${GREEN}" "${NC}"
    printf "%s6. Change the Admin Tool key%s\n" "${GREEN}" "${NC}"
    printf "%s7. Change the Admin Tool port%s\n" "${GREEN}" "${NC}"
    printf "%s =========================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) update_phpmyadmin ;;
        2) update_phpsysinfo ;;
        3) update_opcache_panel ;;
        4) update_memcached_panel ;;
        5) update_redis_panel ;;
        6)
            read -r -p "Nhap mat khau moi: " admin_new_pwd
            htpasswd -b -c /usr/share/nginx/auth/.htpasswd admin "${admin_new_pwd}"
                  sed -i '/admin_pwd=/d' "${FILE_INFO}"
                  echo "admin_pwd=${admin_new_pwd}" >> "${FILE_INFO}"
            clear
            printf "%s\n" "${GREEN}Change Admin Tool success.${NC}"
            menu_admin
            ;;
        7) change_port_admin ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done