#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=====================================%s\n" "${GREEN}" "${NC}"
printf "%s     Backup / Restore data           %s\n" "${GREEN}" "${NC}"
printf "%s=====================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Data backup (Local)%s\n" "${GREEN}" "${NC}"
    printf "%s2. Data recovery (Local)%s\n" "${GREEN}" "${NC}"
    printf "%s3. Delete backup (Local)%s\n" "${GREEN}" "${NC}"
    printf "%s4. Restore / Backup with Google Drive%s\n" "${GREEN}" "${NC}"
    printf "%s5. Set up automatic backup%s\n" "${GREEN}" "${NC}"
    printf "%s ====================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; select_backup;;
        2) clear; select_restore ;;
        3) clear; delete_backup ;;
        4) clear; menu_ggdrive ;;
        5) clear; menu_cronjob ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done