#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s====================%s\n" "${GREEN}" "${NC}"
printf "%s   Cache Manager    %s\n" "${GREEN}" "${NC}"
printf "%s====================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Memcached%s\n" "${GREEN}" "${NC}"
    printf "%s2. Redis%s\n" "${GREEN}" "${NC}"
    printf "%s3. Opcache management%s\n" "${GREEN}" "${NC}"
    printf "%s4. Clear the Cache%s\n" "${GREEN}" "${NC}"
    printf "%s5. Install Memcached%s\n" "${GREEN}" "${NC}"
    printf "%s6. Installing Redis%s\n" "${GREEN}" "${NC}"
    printf "%s =================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; memcached_c ;;
        2) clear; redis_c ;;
        3) clear; manage_opcache ;;
        4) clear; clear_cache ;;
        5) clear; inst_memcached ;;
        6) clear; inst_redis ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n"  "${GREEN}Your choice is not correct. Please choose again.${RED}";;
    esac
done