#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154

CHOICE=1

printf "%s=====================================%s\n" "${GREEN}" "${NC}"
printf "%s         Manage CSF Firewall         %s\n" "${GREEN}" "${NC}"
printf "%s=====================================%s\n" "${GREEN}" "${NC}"
printf "%sCSF GUI:%s %s%s%s\n" "${GREEN}" "${NC}" "${RED}" "https://${IPADDRESS}:${csf_port}" "${NC}"
printf "%s======================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Open Port%s\n" "${GREEN}" "${NC}"
    printf "%s2. Test Block IP%s\n" "${GREEN}" "${NC}"
    printf "%s3. Block IP%s\n" "${GREEN}" "${NC}"
    printf "%s4. Remove Block IP%s\n" "${GREEN}" "${NC}"
    printf "%s5. Remove Block all IP%s\n" "${GREEN}" "${NC}"
    printf "%s6. Allow IP%s\n" "${GREEN}" "${NC}"
    printf "%s7. Grant access to the CSF GUI%s\n" "${GREEN}" "${NC}"
    printf "%s8. Restart CSF%s\n" "${GREEN}" "${NC}"
    printf "%s9. Enable CSF%s\n" "${GREEN}" "${NC}"
    printf "%s10. Disable CSF%s\n" "${GREEN}" "${NC}"
    printf "%s ============================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; csf_open_port ;;
        2)
            read -r -p "Enter the IP you want to enable: " ip
            csf -g "${ip}"
            echo ""
            menu_csf
            ;;
        3)
            read -r -p "Enter the IP you want to block: " ip
            csf -d "${ip}"
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Block IP success.${NC}"
            echo ""
            menu_csf
            ;;
        4)
            read -r -p "Enter the IP you want to unblock: " ip
            csf -dr "${ip}"
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Go Block IP success.${NC}"
            echo ""
            menu_csf
            ;;
        5)
            csf -tf
            csf -df
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Remove Block all IP success.${NC}"
            echo ""
            menu_csf
            ;;
        6)
            read -r -p "Enter the IP you want to allow: " ip
            csf -a "${ip}"
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Allow IP success.${NC}"
            echo ""
            menu_csf
            ;;
        7)
            read -r -p "Enter the IP you want to grant access to the CSF GUI: " ip
            cat >> "/etc/csf/ui/ui.allow" << EOcsfui
${ip}
EOcsfui
            csf -a "${ip}"
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Access granting CSF GUI success.${NC}"
            echo ""
            menu_csf
            ;;
        8)
            csf -x
            csf -e
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Restart CSF success.${NC}"
            echo ""
            menu_csf
            ;;
        9)
            csf -x
            systemctl stop csf
            systemctl stop lfd
            systemctl disable csf
            systemctl disable lfd
            clear
            printf "%s\n" "${GREEN}Enable CSF success.${NC}"
            echo ""
            menu_csf
            ;;
        10)
            csf -e
            systemctl start csf
            systemctl start lfd
            systemctl enable csf
            systemctl enable lfd
            clear
            printf "%s\n" "${GREEN}Disable CSF success.${NC}"
            echo ""
            menu_csf
            ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n"  "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done