#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s======================%s\n" "${GREEN}" "${NC}"
printf "%s   Domain Management  %s\n" "${GREEN}" "${NC}"
printf "%s======================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Domain list%s\n" "${GREEN}" "${NC}"
    printf "%s2. Add a domain name%s\n" "${GREEN}" "${NC}"
    printf "%s3. Delete domain name%s\n" "${GREEN}" "${NC}"
    printf "%s4. Change domain name%s\n" "${GREEN}" "${NC}"
    printf "%s5. Rewrite Vhost Config%s\n" "${GREEN}" "${NC}"
    printf "%s ==================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; domain_list;;
        2) clear; domain_create ;;
        3) clear; domain_destroy ;;
        4) clear; domain_change ;;
        5) clear; rewrite_config ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done