#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=================================%s\n" "${GREEN}" "${NC}"
printf "%s           Google Drive          %s\n" "${GREEN}" "${NC}"
printf "%s=================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Set up Google Drive%s\n" "${GREEN}" "${NC}"
    printf "%s2. Backup to GG Drive%s\n" "${GREEN}" "${NC}"
    printf "%s3. Recover data from GG Drive%s\n" "${GREEN}" "${NC}"
    printf "%s4. Clear data on GG Drive%s\n" "${GREEN}" "${NC}"
    printf "%s5. Backup list on GG Drive%s\n" "${GREEN}" "${NC}"
    printf "%s6. Delete Google Drive remote%s\n" "${GREEN}" "${NC}"
    printf "%s ================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; ggdrive_connect;;
        2) clear; ggdrive_backup ;;
        3) clear; ggdrive_restore ;;
        4) clear; ggdrive_destroy ;;
        5) clear; ggdrive_list_backup ;;
		    6) clear; ggdrive_del_remote ;;
        0) clear; menu_backup ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done