#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s========================%s\n" "${GREEN}" "${NC}"
printf "%s  Management LEMP Stack %s\n" "${GREEN}" "${NC}"
printf "%s========================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Manager Nginx%s\n" "${GREEN}" "${NC}"
    printf "%s2. PHP management%s\n" "${GREEN}" "${NC}"
    printf "%s3. Database management%s\n" "${GREEN}" "${NC}"
    printf "%s4. FTP management%s\n" "${GREEN}" "${NC}"
    printf "%s5. Log management%s\n" "${GREEN}" "${NC}"
    printf "%s ==================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; menu_nginx;;
        2) clear; menu_php;;
        3) clear; menu_database;;
        4) clear; menu_ftp;;
        5) clear; menu_log;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done