#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s===========================+%s\n" "${GREEN}" "${NC}"
printf "%s  Management Let's Encrypt  %s\n" "${GREEN}" "${NC}"
printf "%s===========================+%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Add Let's Encrypt%s\n" "${GREEN}" "${NC}"
    printf "%s2. Let's Encrypt Wildcard%s\n" "${GREEN}" "${NC}"
    printf "%s3. Check out the deadline%s\n" "${GREEN}" "${NC}"
    printf "%s4. Removed Let's Encrypt%s\n" "${GREEN}" "${NC}"
    printf "%s ========================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; le_create ;;
        2) clear; le_wildcard ;;
        3) clear; le_check_expired ;;
        4) clear; le_remove ;;
        0) clear; menu_ssl ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done