#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s===================%s\n" "${GREEN}" "${NC}"
printf "%s    Log manager    %s\n" "${GREEN}" "${NC}"
printf "%s===================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. See Log Nginx%s\n" "${GREEN}" "${NC}"
    printf "%s2. See Log PHP%s\n" "${GREEN}" "${NC}"
    printf "%s3. See Log MariaDB%s\n" "${GREEN}" "${NC}"
    printf "%s4. View by domain name%s\n" "${GREEN}" "${NC}"
    printf "%s ==================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            clear
            printf "%s\n" "${RED}Show the last 10 log...${NC}"
            echo ""
            tail /var/log/nginx/error.log
            printf "%s\n" "${RED}Log file location: /var/log/nginx/error.log${NC}"
            menu_log
            ;;
        2)
            clear
            printf "%s\n" "${RED}Display the last 10 log...${NC}"
            echo ""
            tail /var/log/php-fpm/error.log
            printf "%s\n" "${RED}Log file location: /var/log/php-fpm/error.log${NC}"
            menu_log
            ;;
        3)
            clear
            printf "%s\n" "${RED}Show the last 20 log...${NC}"
            echo ""
            tail /var/log/mysql/mysqld.log
            printf "%s\n" "${RED}Log file location: /var/log/mysql/mysqld.log${NC}"
            menu_log
            ;;
        4) clear; domain_log;;
        0) clear; menu_lemp ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done