#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154

CHOICE=1

printf "%s==================================%s\n" "${GREEN}" "${NC}"
printf "%s           PHP management         %s\n" "${GREEN}" "${NC}"
printf "%s==================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Check for default PHP version%s\n" "${GREEN}" "${NC}"
    printf "%s2. Check PHP version 2%s\n" "${GREEN}" "${NC}"
    printf "%s3. Update PHP version%s\n" "${GREEN}" "${NC}"
    printf "%s4. PHP future review              %s\n" "${GREEN}" "${NC}"
    printf "%s5. Configure PHP parameters          %s\n" "${GREEN}" "${NC}"
    printf "%s6. Change the free PHP version%s\n" "${GREEN}" "${NC}"
    #printf "%s7. Thay doi phien ban PHP 2       %s\n"
    printf "%s7. Install PHP version 2    %s\n" "${GREEN}" "${NC}"
    printf "%s =================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) php -v; menu_php ;;
        2)
            if [[ "${php2_release}" != "yes" ]]; then
                clear
                printf "${RED}You have not installed the collection PHP version 2.%s\n"
            else
                #https://www.howtoforge.com/tutorial/linux-grep-command/
                #https://stackoverflow.com/a/6284370
                php2_ver=$(grep -w "php2_version" "${FILE_INFO}" | cut -f2 -d'=')
                echo ""
                echo "PHP version 2 is used as: ${php2_ver}"
                echo ""
            fi
            menu_php
            ;;
        3)
            yum -y update php-fpm
            clear
            printf "%s\n" "${RED}The default PHP version is up to date.${NC}"

            if [[ "${php2_release}" == "yes" ]]; then
                yum -y update "${php2_version}"-php-fpm
                clear
                printf "%s\n" "${RED}PHP 2 is the latest version${NC}"
            fi
            menu_php
            ;;
        4)
            systemctl restart php-fpm
            if [[ "${php2_release}" == "yes" ]]; then
                systemctl restart "${php2_version}"-php-fpm
            fi
            clear
            printf "%s\n" "${GREEN}Restart PHP success..${NC}"
            menu_php
            ;;
        5) clear; php_setting ;;
        6) clear; php1_change ;;
        #7) clear; php2_change ;;
        7) clear; php_inst_ver_2 ;;
        0) clear; menu_lemp ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done