#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s===============================================%s\n" "${GREEN}" "${NC}"
printf "%s                     VPS management              %s\n" "${GREEN}" "${NC}"
printf "%s===============================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Webserver state%s\n" "${GREEN}" "${NC}"
    printf "%s2. VPS information%s\n" "${GREEN}" "${NC}"
    printf "%s3. Other information%s\n" "${GREEN}" "${NC}"
    printf "%s4. See the progress on VPS%s\n" "${GREEN}" "${NC}"
    printf "%s5. Check VPS capacity%s\n" "${GREEN}" "${NC}"
    printf "%s6. Change SSH information%s\n" "${GREEN}" "${NC}"
    printf "%s7. Updating VPS%s\n" "${GREEN}" "${NC}"
    printf "%s8. Update configuration (After upgrading VPS)%s\n" "${GREEN}" "${NC}"
    printf "%s9. VPS Security (Scan Malware, Naxsi Firewall)%s\n" "${GREEN}" "${NC}"
    printf "%s =============================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; info_webserver ;;
        2) clear; info_vps ;;
        3) clear; info_other ;;
        4)
            clear
            echo ""
            printf "%s\n" "${GREEN}Opening htop. To Exit from the htop bam CTRL + C${NC}"
            echo ""
            sleep 4
            htop
            ;;
        5)
            clear
            echo ""
            printf "%s\n" "${GREEN}Checking VPS capacity${NC}"
            echo ""
            sleep 3
            df -h
            menu_vps
            ;;
        6) clear; menu_ssh ;;
        7)
            printf "%s\n" "${RED}}Note: The latest version of the system can cause unexpected problems.${NC}"
            read -r -p "You definitely want to update (y/N)" confirm_update
            if [[ ${confirm_update} =~ ^([yY])$ ]]; then
                echo "Prepare to update VPS..."
                sleep 2
                yum -y update
                clear
                printf "%s\n" "${GREEN}The update is completed.${NC}"
            else
                clear
                printf "%s\n" "${RED}You have chosen to Cancel the update.${NC}"
            fi

            menu_vps
            ;;
        8) change_all_parameter ;;
        9) clear; menu_security ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done