#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=========================================%s\n" "${GREEN}" "${NC}"
printf "%s            Manage WordPress             %s\n" "${GREEN}" "${NC}"
printf "%s=========================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Automatic WordPress installation%s\n" "${GREEN}" "${NC}"
    printf "%s2. Check WordPress version%s\n" "${GREEN}" "${NC}"
    printf "%s3. Update WordPress version%s\n" "${GREEN}" "${NC}"
    printf "%s4. Manage Plugins%s\n" "${GREEN}" "${NC}"
    printf "%s5. Database management%s\n" "${GREEN}" "${NC}"
    printf "%s6. Restore / Backup data%s\n" "${GREEN}" "${NC}"
    printf "%s7. Advanced functionality%s\n" "${GREEN}" "${NC}"
    printf "%s8. Change domain name%s\n" "${GREEN}" "${NC}"
    printf "%s9. Change admin password (wp-admin)%s\n" "${GREEN}" "${NC}"
    printf "%s ========================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_auto_install ;;
        2) clear; wp_version ;;
        3) clear; wp_update ;;
        4) clear; wp_menu_plugins ;;
        5) clear; wp_menu_database ;;
        6) clear; wp_menu_backup ;;
        7) clear; wp_menu_advanced ;;
        8) clear; wp_change_domain ;;
        9) clear; wp_change_pass_admin ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done
