#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/helpers/variable_php
source /var/hostvn/menu/helpers/function

confirm(){
    while true
    do
        read -r -p "Do You want to install Memcached ? (y/n) " prompt_memcached
        echo
        if [[ "${prompt_memcached}" =~ ^([yY])$ || "${prompt_memcached}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
        fi
    done
}

set_var(){
    NGINX_PROCESSES=$(grep -c ^processor /proc/cpuinfo)
    MAX_CLIENT=$((NGINX_PROCESSES * 1024))
}

install(){
    if [[ "${OS_VER}" -eq 8 ]]; then
        dnf -y install memcached
    else
        yum -y install memcached
    fi

    if [[ -f "/etc/sysconfig/memcached" ]]; then
        mv /etc/sysconfig/memcached /etc/sysconfig/memcached.bak
        cat >> "/etc/sysconfig/memcached" << EOMEMCACHED
PORT="11211"
USER="memcached"
MAXCONN="${MAX_CLIENT}"
CACHESIZE="${MAX_MEMORY}mb"
OPTIONS="-l 127.0.0.1 -U 0"
EOMEMCACHED
    fi
    semanage permissive -a memcached_t
}

inst_phpmemcachedadmin(){
    cd_dir "${DEFAULT_DIR_TOOL}"
    git clone https://github.com/elijaa/phpmemcachedadmin.git
    rm -rf "${DEFAULT_DIR_TOOL}"/phpmemcachedadmin/docker
    mv phpmemcachedadmin memcached
    chown -R nginx:nginx "${DEFAULT_DIR_TOOL}"/memcached
}

_run(){
    if [ ! -f "/etc/sysconfig/memcached" ]; then
        set_var
        install
        inst_phpmemcachedadmin
        clear
        printf "%s\n" "${GREEN}Memcached installation is successful${NC}"
    else
        printf "%s\n" "${RED}Memcached was already installed.${NC}"
    fi
}

prompt_memcached=""
confirm
if [[ "${prompt_memcached}" =~ ^([yY])$ ]];then
    _run
else
    clear
    printf "%s\n" "${GREEN}You have uninstalled Memcached.${NC}"
fi

menu_cache