#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/helpers/function

select_time(){
    echo "Choose time?"
    PS3='Enter your choice (1-4): '
    options=("Backup 1 times/day" "Backup 1 times/week" "Backup 1 times/month" "Backup 1 times/year" "Cancel creating cronjob")
    select opt in "${options[@]}"
    do
        case $opt in
            "Backup 1 times/day") time="@midnight"; break;;
            "Backup 1 times/week") time="@weekly"; break;;
            "Backup 1 times/month") time="@monthly"; break;;
            "Backup 1 times/year") time="@yearly"; break;;
            "Cancel creating cronjob") time="0"; break;;
            *) printf "%s\n" "${RED}You entered incorret choice, please re-enter.${NC}";;
        esac
    done
}

input_backup_num(){
    echo "Enter the number of backups you want to store: "
    echo "Example: Daily backup and enter 14 - Save the latest 14 backup - Older friends will be rubbed"
    echo "Example: Weekly backup and enter 14 - Record backup 14 * 7 = 98 the most recent day - Older friends will be massaged"
    while true
    do
        read -r -p "Enter your selection [0 = Exit]:" backup_num
        echo
        if [[ "${backup_num}" =~ ^[0-9]+$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
        fi
    done
}

set_backup_num(){
    input_backup_num
    if [[ "${time}" == "@weekly" ]]; then
        backup_num=$((backup_num*7))
    elif [[ "${time}" == "@monthly" ]]; then
        backup_num=$((backup_num*30))
    elif [[ "${time}" == "@yearly" ]]; then
        backup_num=$((backup_num*365))
    else
        backup_num="${backup_num}"
    fi

    sed -i '/backup_num=/d' "${FILE_INFO}"
    echo "backup_num=${backup_num}" >> "${FILE_INFO}"
}

create_cron(){
    crontab -l > backupgg
    echo "${time} /var/hostvn/menu/cronjob/backup_ggdrive.sh >/dev/null 2>&1" >> backupgg
    crontab backupgg
    rm -rf backupgg
}

_run(){
    select_remote
    if [[ -z "${ALERT}" ]]; then
        select_time
        if [ "${time}" == "0" ]; then
            clear
            printf "%s\n" "${RED}Cancel creating cronjob.${NC}"
        else
            set_backup_num
            if [ "${backup_num}" == "0" ]; then
                clear
                printf "%s\n" "${RED}Cancel creating cronjob.${NC}"
            else
                sed -i '/remote/d' "${FILE_INFO}"
                echo "remote=${remote}" >> "${FILE_INFO}"
                create_cron
                clear
                printf "%s\n" "${GREEN}Create a cronjob successfully.${NC}"
                echo ""
            fi
        fi
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
time=""
backup_num=""
cron_exists=$(crontab -l | grep -w 'backup_ggdrive')

if [ -z "${cron_exists}" ]; then
    _run
else
    clear
    printf "%s\n" "${RED}Cronjob already exist.${NC}"
fi

menu_cronjob