#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    if [ -f "/home/${username}/${domain}/public_html/wp-config.php" ]; then
        cd_dir /home/"${username}"/"${domain}"/public_html
        sed -i '/WP_CACHE_KEY_SALT/d' /home/"${username}"/"${domain}"/public_html/wp-config.php
        prefix=$(< /dev/urandom tr -dc '[:lower:]' | head -c"${1:-6}";echo;)
        wp config set WP_CACHE_KEY_SALT "${username}"_"${prefix}" --allow-root
        chow -R "${username}":"${username}" /home/"${username}"/"${domain}"/public_html
        restart_service
        clear
        printf "%s\n" "${GREEN}Generate WP_CACHE_KEY_SALT success.${NC}"
    else
        clear
        printf "%s\n" "${RED}File wp-config.php does not exist.${NC}"
    fi
}

domain=""
select_domain
if [[ -z "${domain}" ]]; then
    clear
    printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
else
    _run "$@"
fi
wp_menu_advanced