#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
    domain=""
    select_domain
    if [[ -n "${domain}" ]]; then
        username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
        cd_dir /home/"${username}"/"${domain}"/public_html
        wp maintenance-mode is-active --allow-root

        if [[ $? == 1 ]]; then
            wp maintenance-mode activate --allow-root
            restart_service
            clear
            printf "%s\n" "${GREEN}Enable maintenance mode successfully.${NC}"
            echo ""
        else
            wp maintenance-mode deactivate --allow-root
            restart_service
            clear
            printf "%s\n" "${GREEN}Disable maintenance mode success.${NC}"
            echo ""
        fi
    else
        clear
        printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
    fi
}

_run
wp_menu_advanced