#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=========================================%s\n" "${GREEN}" "${NC}"
printf "%s             Backup / Restore            %s\n" "${GREEN}" "${NC}"
printf "%s=========================================%s\n" "${GREEN}" "${NC}"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Data Backup (Local)%s\n" "${GREEN}" "${NC}"
    printf "%s2. Recover data (Local)%s\n" "${GREEN}" "${NC}"
    printf "%s3. Back up to Google Drive%s\n" "${GREEN}" "${NC}"
    printf "%s4. Set up automatic backups%s\n" "${GREEN}" "${NC}"
    printf "%s ==========================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_backup ;;
        2) clear; wp_restore ;;
        3) clear; menu_ggdrive ;;
        4) clear; menu_cronjob ;;
        0) clear; menu_wp ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done