#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=========================================%s\n" "${GREEN}" "${NC}"
printf "%s         Configure the cache plugin      %s\n" "${GREEN}" "${NC}"
printf "%s=========================================%s\n" "${GREEN}" "${NC}"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Add configured cache plugins%s\n" "${GREEN}" "${NC}"
    printf "%s2. Delete configuration cache plugins%s\n" "${GREEN}" "${NC}"
    printf "%s ========================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Enter your selection [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; add_plugins_cache ;;
        2) clear; remove_plugins_cache ;;
        0) clear; wp_menu_advanced ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done