#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/helpers/function

backup_confirm(){
    while true
    do
        read -r -p "Do you want to back up data before optimization? (y/n) " promt_backup
        echo
        if [[ "${promt_backup}" =~ ^([yY])$ || "${promt_backup}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n" "${RED}The value you entered is not correct. Please re-enter.${NC}"
        fi
    done
}

backup(){
    if [[ ! -d "/home/backup/${CURRENT_DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${CURRENT_DATE}"/"${domain}"
    fi
    cd_dir /home/"${username}"/"${domain}"
    if [ -f "/home/backup/${CURRENT_DATE}/${domain}/${domain}.tar.gz" ]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz
    fi
    tar -cpzvf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz public_html --exclude "public_html/wp-content/cache"
}

_run(){
    before=$(du -sh /home/"${username}"/"${domain}"/public_html/wp-content/uploads | cut -f1 -d"M")
    clear
    printf "%s\n" "${GREEN}Prepare optimization...${NC}"
    pngquant /home/"${username}"/"${domain}"/public_html/wp-content/uploads/*/*/*.png --quality=75-80 --ext=.png --force
    jpegoptim /home/hathanhxyz/hathanh.xyz/public_html/wp-content/uploads/*/*/*.jpg -m 75
    jpegoptim /home/hathanhxyz/hathanh.xyz/public_html/wp-content/uploads/*/*/*.jpeg -m 75
    after=$(du -sh /home/"${username}"/"${domain}"/public_html/wp-content/uploads | cut -f1 -d"M")
    clear
    printf "%s\n" "${GREEN}Success image optimization${NC}"
    printf "%s\n" "${GREEN}Capacity before optimization:${NC} ${RED}${before}M${NC}"
    printf "%s\n" "${GREEN}Capacity after optimization:${NC} ${RED}${after}M${NC}"
}

promt_backup=""
domain=""
select_domain

if [ -z "${domain}" ]; then
    clear
    printf "%s\n" "${RED}You have selected Cancel action.${NC}"
else
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    backup_confirm
    if [[ "${promt_backup}" =~ ^([yY])$ ]];then
        make_backup_dir "${domain}"
        backup
    fi
    _run
fi

wp_menu_advanced