#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2034
# shellcheck disable=SC2154
source /var/hostvn/menu/helpers/function

set_var(){
    user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
}

_run(){
    set_var
    if [ -f "/home/${user}/${domain}/public_html/wp-config.php" ]; then
        string=$(grep -rnw "/home/${user}/${domain}/public_html/wp-config.php" -e "DISABLE_WP_CRON")

        if [ -z "${string}" ]; then
            sed -i "/WP_DEBUG/a define('DISABLE_WP_CRON', true);" /home/"${user}"/"${domain}"/public_html/wp-config.php
            noti="Disable WP CRON and c Cancel an to Cron Job success."
            if [ ! -f "${WORDPRESS_CRON_DIR}/${domain}" ]; then
                touch "${WORDPRESS_CRON_DIR}"/"${domain}"
            fi

            cron_exists=$(crontab -l | grep -w 'wpcron.sh')
            if [ -z "${cron_exists}" ]; then
                crontab -l > wpcron
                echo "* * * * * /var/hostvn/menu/cronjob/wpcron.sh >/dev/null 2>&1" >> wpcron
                crontab wpcron
                rm -rf wpcron
            fi
        else
            sed -i '/DISABLE_WP_CRON/d' /home/"${user}"/"${domain}"/public_html/wp-config.php
            noti="Getting WP_CRON and all Cronjob success."
            # shellcheck disable=SC2115
            if [ -f "${WORDPRESS_CRON_DIR}/${domain}" ]; then
                rm -rf "${WORDPRESS_CRON_DIR}"/"${domain}"
            fi
        fi
        printf "%s\n" "${GREEN}${noti}${NC}"
    else
        clear
        printf "%s\n" "${RED}File wp-config.php does not exist.${NC}"
    fi
}

ALERT=""
domain=""
select_domain

if [ -n "${domain}" ]; then
    _run
else
    clear
    printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
fi
wp_menu_advanced