#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
    check_mathseo=$(grep -rnw "${VHOST_DIR}/${domain}.conf" -e "rank_math_seo")

    if [ -n "${check_mathseo}" ]; then
        while true
        do
            read -r -p "Detect Rank Math Seo configuration. Do you want to delete Rank Math Scarring configuration? (y/n) " del_rankmath
            echo
            if [[ "${del_rankmath}" =~ ^([yY])$ ]]; then
                sed -i '/rank_math_seo/d' "${VHOST_DIR}"/"${domain}".conf
                break
            elif [[ "${del_yoast}" =~ ^([nN])$ ]]; then
                ALERT=$(printf "%s\n" "${RED}You have chosen not to delete the Yoast Seo config. Cancel the configuration of Rank Math Seo.${NC}")
                break
            else
                printf "%s\n" "${RED}The value you entered is not correct, please re-enter.${NC}"
            fi
        done
    fi

    if [[ -z "${ALERT}" ]]; then
        check_yoastseo=$(grep -rnw "${VHOST_DIR}/${domain}.conf" -e "yoast_seo")
        sed -i '/plugins_seo=/d' "${USER_DIR}"/."${domain}".conf
        if [[  -n "${check_yoastseo}" ]]; then
            sed -i '/yoast_seo/d' "${VHOST_DIR}"/"${domain}".conf
            echo "plugins_seo=" >> "${USER_DIR}"/."${domain}".conf
            restart_service
            printf "%s\n" "${GREEN}Enable configuration Yoast Seo success.${NC}"
        else
            echo "plugins_seo=yoast_seo" >> "${USER_DIR}"/."${domain}".conf
            sed -i '/index.html/a include /etc/nginx/wordpress/yoast_seo.conf;' "${VHOST_DIR}"/"${domain}".conf
            restart_service
            printf "%s\n" "${GREEN}Disable Yoast Seo success.${NC}"
        fi
    else
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
domain=""
del_rankmath=""
select_domain
if [ -z "${domain}" ]; then
    clear
    printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
else
    _run
fi

wp_menu_advanced