#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

input(){
    while true
    do
        echo "Username does not contain special characters and must be 5 characters in length."
        read -r -p "Enter the user you want to change the password for [0 = Exit]: " ftp_user
        echo
        if validate_user "${ftp_user}"; then
            break
        else
            clear
            printf "%s\n" "${RED}User does not exist, please re-enter.${NC}"
        fi
    done

    ftp_pwd=$(gen_pass "$@")
}

_change_pass(){
    pure-pw passwd "${ftp_user}" <<EOF
${ftp_pwd}
${ftp_pwd}
EOF
    pure-pw mkdb
    systemctl restart pure-ftpd
    string=$(grep -rnw "${USER_DIR}" -e "${ftp_user}" | cut -f1 -d':')
    if [ -n "${string}" ]; then
        for i in ${string} ; do
            sed -i '/user_pass/d' "${i}"
            echo "user_pass=${ftp_pwd}" >> "${i}"
        done
    fi
}

_run(){
    if [[ -f "/etc/pure-ftpd/pureftpd.passwd" ]]; then
        if ! if_pureftpd_user_exists "${ftp_user}"; then
            ALERT=$(printf "%s\n" "${RED}FTP User does not exist.${NC}")
        fi

        if [[ -z "${ALERT}" ]]; then
            _change_pass
            clear
            printf "%s\n" "${GREEN}Change password FTP success.${NC}"
            printf "%s\n" "${GREEN}The new password is:${NC} ${RED}${ftp_pwd}${NC} "
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    else
        clear
        printf "%s\n" "${RED}No FTP users exist on VPS.${NC}"
    fi
}

ALERT=""
ftp_user=""
pureftpd_status="$(pgrep -f pure-ftpd)"

if [ -z "${pureftpd_status}" ]; then
    clear
    printf "%s\n" "${RED}PURE-FTP is not working or is not installed. Please check again.${NC}"
else
    input "$@"
    if [ "${ftp_user}" == "0" ]; then
        clear
        printf "%s\n" "${RED}You have Canceled the action.${NC}"
    else
        _run
    fi
fi

menu_ftp