#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    pureftpd_status="$(pgrep -f pure-ftpd)"
    ftp_port=$(grep -w "ftp_port" "${FILE_INFO}" | cut -f2 -d'=');
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
}

input(){
    while true
    do
        echo "Username does not contain special characters and must be 5 characters in length."
        read -r -p "Enter the user you want to create [0 = Exit]: " ftp_user
        echo
        if validate_user "${ftp_user}" || [ "${ftp_user}" == "0" ] ; then
            break
        else
            clear
            printf "%s\n" "${RED}User is not in the correct format, please enter it again.${NC}"
        fi
    done

    if [ "${ftp_user}" != "0" ]; then
        ftp_pwd=$(gen_pass "$@")
        echo "Click on the link allowed to access. For example: /home/example, /home/example/example.com/public_html"
        read -r -p "Enter the path [0 = Exit]: " ftp_path
    fi
}

show_info(){
    clear
    echo ""
    printf "Port FTP: %s\n" "${ftp_port}"
    printf "FTP User: %s\n" "${ftp_user}"
    printf "FTP Pass: %s\n" "${ftp_pwd}"
    sleep 3
    echo ""
}

_create(){
    pure-pw useradd "${ftp_user}" -u "${username}" -g "${username}" -d "${ftp_path}" <<EOF
${ftp_pwd}
${ftp_pwd}
EOF
    pure-pw mkdb
    systemctl restart pure-ftpd
}

_run(){
    set_var

    if if_pureftpd_user_exists "${ftp_user}"; then
        ALERT=$(printf "%s\n" "${RED}User already exist.${NC}")
    fi

    if [ "${ftp_path}" == "/" ]; then
        ALERT=$(printf "%s\n" "${RED}Access path is incorrect.${NC}")
    fi

    if [[ ! -d "${ftp_path}" ]]; then
        ALERT=$(printf "%s\n" "${RED}Access path does not exist.${NC}")
    fi

    if [[ -z "${ALERT}" ]]; then
        _create
        clear
        show_info
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
ftp_user=""
pureftpd_status="$(pgrep -f pure-ftpd)"

if [ -z "${pureftpd_status}" ]; then
    clear
    printf "%s\n" "${RED}PURE-FTP does not work or is not installed. Please check back.${NC}"
else
    select_domain
    if [ -z "${domain}" ]; then
        clear
        printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
    else
        input "$@"
        if [[ "${ftp_user}" == "0" || "${ftp_path}" == "0" ]]; then
            clear
            printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
        else
            _run
        fi
    fi
fi

menu_ftp
