#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

input(){
    while true
    do
        echo "The username is not unique and has 5-year-old password."
        read -r -p "1. Enter the database name [0 = Exit]: " db_name
        echo
        if validate_user "${db_name}"; then
            break
        else
            printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
        fi
    done

    if [ "${db_name}" != "0" ]; then
        while true
        do
            echo "The username is not unique and has 5-year-old password."
            read -r -p "Enter Mysql User [0 = Exit]: " db_user
            echo
            if validate_user "${db_user}"; then
                break
            else
                printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
            fi
        done

        if [ "${db_user}" != "0" ]; then
            while true
            do
                read -r -p "Verify more database? (y/n): " promtp_db
                echo
                if [[ "${promtp_db}" =~ ^([yY])$ || "${promtp_db}" =~ ^([nN])$ ]]; then
                    break
                else
                    printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
                fi
            done
            password=$(gen_pass "$@")
        fi
    fi
}

validate(){
    check_database "${db_name}"
    check_mysql_user "${db_user}"
}

create_db(){
    printf "%s\n" "${GREEN}Create a new database...${NC}"
    mysql -e "CREATE DATABASE IF NOT EXISTS ${db_name}"
    mysql -e "CREATE USER IF NOT EXISTS '${db_user}'@'localhost' IDENTIFIED BY '$password'"
    mysql -e "GRANT ALL PRIVILEGES ON ${db_name}.* TO '${db_user}'@'localhost'"
    mysql -e "FLUSH PRIVILEGES"
    clear
    printf "%s\n" "${GREEN}Added databse success.${NC}"
}

show_info(){
    clear
    printf "DB_Name    : s%\n" "${RED}${db_name}${NC}"
    printf "DB_User    : s%\n" "${RED}${db_user}${NC}"
    printf "DB_Password: s%\n" "${RED}${password}${NC}"
    echo ""
    sleep 3
}

_run(){
    if [[ ${promtp_db} =~ ^([yY])$  ]]; then
       validate

        if [ -z "${ALERT}" ]; then
            create_db
            show_info
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    else
        clear
        printf "%s\n" "${RED}You have Canceled add database.${NC}"
    fi
}

ALERT=""
promtp_db=""
db_name=""
db_user=""
input "$@"

if [ "${db_name}" == "0" ]; then
    clear
    printf "%s\n" "${RED}You have Canceled add database.${NC}"
else
    if [ "${db_user}" == "0" ]; then
        clear
        printf "%s\n" "${RED}You have Canceled add database.${NC}"
    else
        _run "$@"
    fi
fi

menu_database