#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

confirm_delete(){
    while true
    do
        read -r -p "Do you want to delete the backup? (y/n) " promt_delete
        echo
        if [[ "${promt_delete}" =~ ^([yY])$ || "${promt_delete}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
        fi
    done
}

_delete(){
    rm -rf /home/backup/"${date}"/"${domain}"/"${domain}".sql
}

_run(){
    list_backup

    if [ -z "${date}" ]; then
        clear
        printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
    else
        if [ -z "${domain}" ]; then
            clear
            printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
        else
            if ! check_backup_empty "${date}" "${domain}"; then
                ALERT="%s\n" "${RED}This domain has no backup.${NC}"
            fi

            if [[ -z "${ALERT}" ]]; then
                _delete
                clear
                printf "%s\n" "${GREEN}Delete backup success.${NC}"
            else
                clear
                printf "%s\n" "${ALERT}"
            fi
        fi
    fi
}

ALERT=""
promt_delete=""
date=""
domain=""

confirm_delete
if [[ "${promt_delete}" =~ ^([yY])$ ]]; then
    _run
else
    clear
    printf "%s\n" "${RED}Ban da Cancel xoa backup.${NC}"
fi
menu_backup