#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

printf "%s============%s" "${GREEN}" "${NC}"
printf "%sDelete the database%s" "${GREEN}" "${NC}"
printf "%s============%s" "${GREEN}" "${NC}"

list_db(){
    echo "Database list on VPS"
    #https://stackoverflow.com/a/50053525
    #https://dba.stackexchange.com/a/69667
    mysql -e "SHOW DATABASES WHERE \`Database\` NOT IN('information_schema', 'phpmyadmin', 'mysql', 'performance_schema')"
    echo
}

input(){
    while true
    do
        echo "The username is not unique and has 5-year-old password."
        read -r -p "Enter the database name [0 = Exit]: " db_name
        echo
        if validate_user "${db_name}"; then
            break
        else
            printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
        fi
    done

    if [ "${db_name}" != "0" ]; then
        while true
        do
            read -r -p "Confirm database delete? (y/n): " prompt_destroy
            echo
            if [[ "${prompt_destroy}" =~ ^([yY])$ || "${prompt_destroy}" =~ ^([nN])$ ]]; then
                break
            else
                printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
            fi
        done
    fi
}

delete_db(){
    if [[ "${prompt_destroy}" =~ ^([yY])$ ]]; then
        printf "%s\n" "${GREEN}Delete database is in progress...${NC}"
        sleep 1
        mysql -e "DROP DATABASE IF EXISTS ${db_name}"
        clear
        printf "%s\n" "${GREEN}Delete database success.${NC}"
    else
        clear
        printf "%s\n" "${RED}You have Canceled delete database.${NC}"
    fi
}

_run(){
    list_db
    input

    if [ "${db_name}" != "0" ]; then
        delete_db
    else
        clear
        printf "%s\n" "${RED}Ban da Cancel xoa database.${NC}"
    fi

}

db_name=""
prompt_destroy=""

_run
menu_database