#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

confirm_restore(){
    while true
    do
        read -r -p "You want to recover data ? (y/n) " promt_restore
        echo
        if [[ "${promt_restore}" =~ ^([yY])$ || "${promt_restore}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
        fi
    done
}

_restore(){
    cd_dir /home/backup/"${date}"/"${domain}"
    mysql -uadmin -p"${mysql_pwd}" "${db_name}" < "${db_name}".sql
}

_run(){
    set_var
    if if_is_wordpress "${username}" "${domain}"; then
        printf "%s\n" "${RED}Website using WordPress. Please use the Wordpress Management Menu to restore.${NC}"
    else
        check_backup_exists "${date}" "${domain}"

        if ! check_backup_empty "${date}" "${domain}";
        then
            ALERT="%s\n" "${RED}This domain has no backup.${NC}"
        fi

        if [ ! -f "/home/backup/${date}/${domain}/${db_name}.sql" ]; then
            ALERT="%s\n" "${RED}This domain has no backup.${NC}"
        fi

        if [[ -z "${ALERT}" ]]; then
            empty_db
            _restore
            clear
            printf "%s\n" "${GREEN}Successful data recovery.${NC}"
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    fi
}

if [[ $(ls -A "${USER_DIR}") ]]; then
    promt_restore=""
    date=""
    domain=""
    ALERT=""

    confirm_restore
    if [[ "${promt_restore}" =~ ^([yY])$ ]]; then
        list_backup
        if [ -z "${date}" ]; then
            clear
            printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
        else
            if [ -z "${domain}" ]; then
                clear
                printf "%s\n" "${RED}You have chosen to cancel the action${NC}"
            else
                _run
            fi
        fi
    else
        clear
        printf "%s\n" "${RED}You have chosen to cancel data recovery.${NC}"
    fi
else
    printf "%s\n" "${RED}There are no domain names on VPS.${NC}"
fi

select_restore