#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

#shellcheck disable=SC2154
#shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

confirm_restore_source(){
    while true
    do
        read -r -p "You want to restore data? (y/n) " promt_restore_source
        echo
        if [[ "${promt_restore_source}" =~ ^([yY])$ || "${promt_restore_source}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Value is not correct. Please re-enter.${NC}"
        fi
    done
}

_restore(){
    if [[ ! -d "/home/${username}/${domain}/public_html" ]]; then
        mkdir -p /home/"${username}"/"${domain}"/public_html
    fi
    cd_dir /home/backup/"${date}"/"${domain}"
    rm -rf /home/"${username}"/"${domain}"/public_html/*
    tar xvzf /home/backup/"${date}"/"${domain}"/"${domain}".tar.gz -C /home/"${username}"/"${domain}"/
    chown -R "${username}":"${username}" /home/"${username}"
}

_run(){
    set_var

    if if_is_wordpress "${username}" "${domain}"; then
        clear
        printf "%s\n" "${RED}This website uses WordPress, please use Menu 7 - 6..${NC}"
        return 1
    fi

    if check_backup_exists "${date}" "${domain}";then
        if ! check_backup_empty "${date}" "${domain}" || [ ! -f "/home/backup/${date}/${domain}/${domain}.tar.gz" ];
        then
            ALERT="%s\n" "${RED}This domain has no backup.${NC}"
        fi
    else
        ALERT="%s\n" "${RED}This domain has no backup.${NC}"
    fi

    if [[ -z "${ALERT}" ]]; then
        _restore
        clear
        printf "%s\n" "${GREEN}Successful data recovery.${NC}"
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

if [[ $(ls -A "${USER_DIR}") ]]; then
    ALERT=""
    promt_restore_source=""
    date=""
    domain=""

    confirm_restore_source
    if [[ "${promt_restore_source}" =~ ^([yY])$ ]]; then
        list_backup
        if [ -z "${date}" ]; then
            clear
            printf "%s\n" "${RED}You have chosen to cancel data recovery.${NC}"
        else
            if [ -z "${domain}" ]; then
                clear
                printf "%s\n" "${RED}You have chosen to cancel data recovery.${NC}"
            else
                _run
            fi
        fi
    else
        clear
        printf "%s\n" "${RED}You have chosen to cancel data recovery.${NC}"
    fi
else
    printf "%s\n" "${RED}There are no domain names on VPS.${NC}"
fi

select_restore