#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s===================%s\n" "${GREEN}" "${NC}"
printf "%s  Data backup  %s\n" "${GREEN}" "${NC}"
printf "%s===================%s\n" "${GREEN}" "${NC}"
echo ""

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Source code backup%s\n" "${GREEN}" "${NC}"
    printf "%s2. Database backup%s\n" "${GREEN}" "${NC}"
    printf "%s3. Full backup%s\n" "${GREEN}" "${NC}"
    printf "%s ================%s\n" "${GREEN}" "${NC}"
    read -r -p " Click on your choice [0 = Exit] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; backup_source;;
        2) clear; backup_db ;;
        3) clear; backup_full ;;
        0) clear; menu_backup ;;
        *) clear; printf "%s\n" "${RED}Your choice is not correct. Please choose again.${NC}";;
    esac
done