#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

printf "%s========================%s\n" "${GREEN}" "${NC}"
printf "%s Cau hinh Let's Encrypt %s\n" "${GREEN}" "${NC}"
printf "%s========================%s\n" "${GREEN}" "${NC}"
echo

validate(){
    check_nginx_status
    check_a_record "${domain}"
}

sign_ssl(){
    /usr/local/bin/certbot-auto --nginx --no-bootstrap -d "${domain}" -d www."${domain}"
}

auto_renew(){
    cron_exists=$(crontab -l | grep -w 'certbot-auto')
    if [ -z "${cron_exists}" ]; then
        crontab -l > certbot
        echo "0 3 * * * /usr/local/bin/certbot-auto renew && service nginx restart >/dev/null 2>&1" >> certbot
        crontab certbot
        rm -rf certbot
    fi
}

restart_nginx(){
    systemctl restart nginx.service
}

_run(){
    validate

    if [ -z "${ALERT}" ]; then
        sign_ssl
        sed -i "s/listen 443 ssl;/listen 443 ssl http2;/g" "${VHOST_DIR}"/"${domain}".conf
        sleep 2
        restart_nginx
        clear
        printf "%s\n" "${GREEN}Cau hinh SSL success.${NC}"
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
domain=""

select_domain
if [ -n "${domain}" ]; then
    _run
    menu_letencrypt
else
    clear
    printf "%s\n" "${RED}You have chosen to cancel the action.${NC}"
    menu_letencrypt
fi

